### ISSUE TITLE
[Discussion] Updating PHP to latest versions

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#33]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/65

**Comment by Tob0t** [comment]
Is PHP 7.2 for azure already available or do you know the release date?

**Comment by SyntaxC4** [comment]
Hi @Tob0t,

Would you like to enable PHP 7.2 on Windows or Linux workers of App Service?

**Comment by Tob0t** [comment]
on Windows workers, I found that PHP 7.2 it is already in the D:/Programs (x86)/PHP/ folder but not possible to select in the Application Settings of the App Service

**Comment by SyntaxC4** [comment]
Adding @Jen7714 for instructions.

**Comment by EricSten-MSFT** [comment]
Yes, there was a slight problem with the .ini file.  PHP 7.2 now requires that all extension= / zend_extension= entries remove the '.dll' suffix.  The fix is in the process of being released now, and should be completed worldwide in a couple of weeks.

**Comment by SyntaxC4** [comment]
Thanks for jumping in @EricSten-MSFT :smile:

**Comment by EricSten-MSFT** [comment]
For folks who want to try it out before the fix is rolled out, you can follow the steps [to specify a custom runtime](https://docs.microsoft.com/en-us/azure/app-service/web-sites-php-configure#how-to-use-a-custom-php-runtime), specifying a path of ```D:\Program Files (x86)\PHP\v7.2``` for the binary, and then use an [XDT transform](https://blogs.msdn.microsoft.com/benjaminperkins/2015/03/03/making-changes-to-the-applicationhost-config-on-azure-websites/) to override the ```PHPRC``` setting to point to [a custom .ini](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#using-a-custom-phpini) file where the ```extension= / zend_extension=``` entries have been fixed.

applicationHost.xdt:
```
<?xml version="1.0"?> 
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"> 
  <system.webServer> 
    <fastCgi>
      <application fullPath="D:\Program Files (x86)\PHP\v7.2\php-cgi.exe" xdt:Locator="Match(fullPath)">
        <environmentVariables>
          <environmentVariable name="PHPRC" xdt:Locator="Match(name)" value="d:\home\site\php.ini" xdt:Transform="SetAttributes(value)" />
        </environmentVariables>
      </application>
    </fastCgi>
  </system.webServer> 
</configuration> 
```

The custom .ini file should make sure to remove the '.dll' suffix from all extension= / zend_extension= directives.

**Comment by Tob0t** [comment]
thanks for the info!!

**Comment by bartek-indycki** [comment]
Hi, how to enable sqlsrv in Azure AppService for PHP 7.2?

**Comment by EricSten-MSFT** [comment]
@bartek-indycki The PHP Drivers for SQL Server for PHP 7.2 was recently [released](https://github.com/Microsoft/msphpsql/releases/tag/v5.2.0), and will be integrated into Azure Web Apps for the next release, as was [recently announced](https://github.com/Azure/app-service-announcements/issues/98).  Thank you for your interest!

**Comment by Yunierhg** [comment]
Hi @bartek-indycki , how can I enable the extension of pdo_mysql for version 7.2. (App in Windows)

**Comment by ndrw** [comment]
How long will PHP 5.6 be supported for? The open source PHP version is supported until the end of 2018 (http://php.net/supported-versions.php). Is there anywhere we can see the roadmap for PHP versions?

Thanks!

**Comment by yiliaomsft** [comment]
We're working on plan for PHP 5.6 and 7.0, we will post back here once we finalize the plan.
