### ISSUE TITLE
[Discussion] ASP.NET Core 2.1 now available on App Service

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#51]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/113

**Comment by mayerc-MSFT** [comment]
Nice to see the introduction of [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1) -- especially the Dependency Injection (DI) and Configuration features.

@davidebbo what's the DI and Configuration story for Functions v2? Should we expect something similar to Generic Host?

**Comment by davidebbo** [comment]
@mayerc-MSFT wrong announcement :) This one is  about the availability of Core 2.1 on App Service, and not related to Functions. Please see https://github.com/Azure/Azure-Functions/blob/master/readme.md for the best places to discuss Functions. Thanks!

**Comment by TiagoSoczek** [comment]
Hey @davidebbo, do you know if AppService supports running ASP.NET Core inproc?

https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-0-preview1-improvements-to-iis-hosting/

Thanks!

**Comment by davidebbo** [comment]
@TiagoSoczek the ASP.NET Core team ended up removing the inproc support from the final 2.1 because it wasn't ready for prime time. But I hear it will come back, and when it does App Service will support it.

**Comment by DerAlbertCom** [comment]
Any Timeframe for rolling this out to AzureGermanCloud? Would like to avoid a self contained deployment, because of the needed changes in the build steps.

**Comment by davidebbo** [comment]
@DerAlbertCom ETA for German Cloud is about a week away.

**Comment by TPoise** [comment]
Am I the only one having issues with Azure App Service (through App Service Environment) and this new .NET Core 2.1?  I migrated an app from ASP.NET Core 2.0 to 2.1 following the instructions.  Works locally on MacOS and Windows 10.  Works on Windows Server 2016 with IIS.  I can step through and debug and publish in release mode through VSCode (Mac) and Visual Studio 2017 (Windows 10).  Does not work on Azure App Service, it will instantly "crash" or end after starting up.  

I've tried:
-clearing out the wwwroot folder
-creating a brand new app service 
-remote debugging through VS2017 (process ends before the debugger can attach)
-putting a bunch of `Console.WriteLine` statements throughout my Startup
-running `dotnet .\MyApp.dll` from Kudu (crashes/ends same way)
-deploying as a self-contained app targeting  `win10-x86`
-Turned on verbose debugging, also turned on `.CaptureStartUpErrors(true)` and `.UseSetting(WebHostDefaults.DetailedErrorsKey, "true")`, neither option produced anymore debug information.
-tried wrapping a try/catch/finally around `Main()` in Program.cs, program ends abruptly and nothing from my finally block is ever ran.

`dotnet --info` from Kudu says:
`Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba
`

Error message from eventlog.xml: ` <Event>
        <System>
            <Provider Name=".NET Runtime"/>
            <EventID>1023</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2018-06-03T02:48:08Z"/>
            <EventRecordID>41156046</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF2BBF78</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application: dotnet.exe
CoreCLR Version: 4.6.26515.7
Description: The process was terminated due to an internal error in the .NET Runtime at IP 55D1931D (55C00000) with exit code 80131506.
</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1000</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2018-06-03T02:48:08Z"/>
            <EventRecordID>41156843</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF2BBF78</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application 'MACHINE/WEBROOT/APPHOST/MYAPP' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\MyApp.dll', ErrorCode = '0x80004005 : c0000005.</Data>
        </EventData>
    </Event>`

From my stdout logs, I can see it starting up, but then the log file stops and I get the dreaded IIS 502.5 Process Failure error.  Logs:

`Hosting environment: Development
Content root path: D:\home\site\wwwroot
Now listening on: http://127.0.0.1:30460
Application started. Press Ctrl+C to shut down.` 

And it ends after that.  Occassionally a request for favicon.ico will show or come through, but the app always crashes.

**Comment by davidebbo** [comment]
@TPoise it turns out there is indeed an issue with App Service Environment (or regular Web Apps that use a vnet). Good news is that there is a fix, and it should be deploy by the middle of next week. Apologies for not mentioning it here, which would have saved you some headache. You'll know you have the fix when you go to the Kudu root and you see "Azure App Service" being version 74.x (you probably have 73.x right now).

**Comment by noelstieglitz** [comment]
@davidebbo - Is there a github issue for the issue with ASEs?

**Comment by davidebbo** [comment]
@noelbundick I don't think so, and generally GitHub is not used to track App Service issues (this repo is used for announcements). We can use this thread for updates on this issue.

**Comment by xt0rted** [comment]
In general 2.1 looks to be working ok, but I'm having issues getting the app insights hosting startup package to load (also found it's not loaded on my existing 2.0 site as well). The app services hosting package looks to be loading ok, just not the app insights one. I added my findings to https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/568#issuecomment-394189143 which was opened a few months ago about this problem.

**Comment by mmcconnell1618** [comment]
@TPoise I'm also having issues with 2.1 in Azure. I upgraded from a 2.0 web app to 2.1 and now I just get 500 errors and a blank page in Azure. There was an extension for the 2.1 preview. Do I need any extension installed? App Service Version 74 according to Kudu.

**Comment by davidebbo** [comment]
@mmcconnell1618 no extension for the final bits. You need to delete all any previous extensions, or try on a clean app.

**Comment by xt0rted** [comment]
@davidebbo without the extension `Microsoft.AspNetCore.AzureAppServices.HostingStartup` doesn't load. How do we get this to load, or is this package not needed now either? If it's not needed then what's it even used for?

**Comment by davidebbo** [comment]
@DamianEdwards @muratg can you help answer this question about `Microsoft.AspNetCore.AzureAppServices.HostingStartup`?

**Comment by mmcconnell1618** [comment]
Deploying to a new, clean, app seems to have resolved the issue. Not sure what was left in the old app that was hanging things. Thank you!

**Comment by DamianEdwards** [comment]
The package itself is not required in the app dependency graph. The AppInsights site extension will set the appropriate env vars to instruct the .NET Core runtime to load the required assemblies (including the hosting startup) from its own location.

**Comment by louislewis2** [comment]
I am not sure who is to thank for getting the version 74 fix out so fast, but many thanks!
It was a terrible 24 hour fault finding mission, till I came upon this post.

**Comment by xt0rted** [comment]
So `Microsoft.AspNetCore.AzureAppServices.HostingStartup` and the `ASP.NET Core Extensions` extension aren't needed, got it.

Regarding AI, I have two different situations going on. The first is with the 2.0 version of my site which I noticed while trying to update it to 2.1. Some time between February and now the automatic AI stuff stopped working. There's also now two AI site extensions in the gallery with different versions. My site had the 2.5.4 version installed, once I replaced it with the 2.6.2 version the JS snippet started showing up on my site again.

The second issue is with the 2.1 version of the same site. With the 2.6.2 version of the AI site extension I'm still not getting the JS snippet on the page or live metrics, and when I go to the extension page it says:
>Cannot retrieve application insight's attach status: either the web application is not running, or some error has occured during initialization. Try starting the webapplication by opening the web application url.

I've tested this on two different 2.1 projects, one's my updated site and the other is a file new project, and neither loads the AI startup package and both give the same error on the extension page.

**Comment by xt0rted** [comment]
I just found that my webjobs haven't been running since 2.1 was installed on my build server. I'm using sdk style projects but targeting .net 4.7.1 and there's a [bug/regression](https://github.com/aspnet/websdk/issues/347) with the publish task for this combo. The `run.cmd` gets generated with `dotnet WebJob.exe` instead of `WebJob.exe` which results in the following error:
```
[06/08/2018 21:45:56 > 68806b: ERR ] A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\local\Temp\jobs\continuous\Emailer\sm0s1wr1.kdr\'.
[06/08/2018 21:45:56 > 68806b: ERR ] Failed to run as a self-contained app. If this should be a framework-dependent app, add the D:\local\Temp\jobs\continuous\Emailer\sm0s1wr1.kdr\Emailer.runtimeconfig.json file specifying the appropriate framework.
```

The two fixes I found are:
1. Delete the `run.cmd` files (quick fix for production)
2. Add a `global.json` to your project and pin the sdk to `2.1.200` until this is resolved

With my setup I'm building & packaging on AppVeyor, so this isn't a kudu/app services specific issue, and it can effect you even if you're not targeting .net core.

**Comment by davidebbo** [comment]
@xt0rted yep, that's indeed an issue to be aware of (and has decent workarounds as you point out).

**Comment by mchallenger88** [comment]
I've deployed a asp.net core 2.1 web api to a new App Service, and get a 500 Internal Server error. It works locally. Any thoughts?

**Comment by mchallenger88** [comment]
Awesome. Thank you. I used the Kudu console and discovered that I had a reference in startup.cs that was triggering an error. Much appreciated!

**Comment by xt0rted** [comment]
Re: my AI comments at https://github.com/Azure/app-service-announcements-discussions/issues/51#issuecomment-394190602

I just updated the AI site extension from 2.6.2 to 2.6.4 and the lightup feature is working now (the tag helper is automatically being included & writing out the JS snippet). I'm not referencing the hosting startup package or wiring up AI in my `Program.cs` or `Startup.cs`, so this issue looks to have been fixed in one of the newer versions of the site extension.

**Comment by ru-sh** [comment]
My app service started to fail on start after adding a reference to Microsoft.AspNetCore.AzureKeyVault.HostingStartup with same error:

`Failed to load the dll from [D:\home\site\wwwroot\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [D:\home\site\wwwroot\`
