### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.11933 Preview release

### ISSUE THREAD

**Issue by alrod** [Azure/app-service-announcements-discussions#58]
Discussion issue for the Azure Functions Runtime 2.0.11933 Preview release

**Comment by nzthiago** [comment]
What's the github issue entry for "HttpTrigger does not return response content properly" mentioned in the release notes? Want to read more about this issue as I think we've just run into it

**Comment by TurtleBeach** [comment]
in 2.0.11888 (Java for sure, probably other languages), if you create a response that you intend to be interpreted as a JSON object along with returning an HTTP error code, rather than the client seeing your JSON object it will see only a "canned" string from some mysterious "Custom Error Module". If the return code is ACCEPTED (202) or OK (200), you the expected JSON is returned (if you defined a JSON payload)

**Comment by TurtleBeach** [comment]
In a different thread, which I have lost track of, the syntax for returning an object has changed. You now have to do something like request.createResponseBuilder(HttpStatus.OK).body("Hello, " + name).build(), where the argument to "body" can be (in Java) a HashMap which will result in a JSON body for the receiver.

**Comment by pragnagopa** [comment]
@TurtleBeach  - Breaking changes for Java Http functions will be part of the next release.

**Comment by jdneo** [comment]
@pragnagopa Is there any ETA for the next release?
