### ISSUE TITLE
[Question] Is AspnetCore 2.2 ANCM deployed on app service ?

### ISSUE THREAD

**Issue by Axel3232** [Azure/app-service-announcements-discussions#78]
Hi, 

 .NET Core 2.2 and ASPNET Core 2.2 have been depoyed to app services : 

```.NET Core SDKs installed:
...
  2.2.100 [D:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 2.1.5 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
````

but how to know if the ANCM 2.2 with the inproc hosting model has been deployed ? It looks like it has not been deployed on my region, since IIS fail at startup with inproc settings.

Do you have any timeframe for that ?

Thx

**Comment by CodingGorilla** [comment]
I am pretty sure it has **not** been deployed, as every time my CD publishes my ASP.Net Core 2.2 application, I have to log in and change the web.config in my Azure Web App back to `AspNetCoreModule` rather than `AspNetCoreModuleV2`.  I've been doing this for a couple of weeks now, so I would also be curious if there's an ETA on ANCM v2.

**Comment by bschapendonk** [comment]
In the .NET Core 2.2 SDK some defaults have changed.

To change back to the 2.1 behavior (aka. use ANCMv1) just add the following `<AspNetCoreModuleName>AspNetCoreModule</AspNetCoreModuleName>` to the main <PropertyGroup>of the project that is published.
Or alternatively, set it using the following command `dotnet publish /p:AspNetCoreModuleName=AspNetCoreModule`.

Be aware that new projects created using the .NET Core 2.2 SDK also add a `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`, I don't know if ANCMv1 will trip over this, buy you can comment it out or set it to `OutOfProcces` to get the v1 behavior.

By the way, this is documented, although poorly discover-able here https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-known-issues.md

**Comment by CodingGorilla** [comment]
Unless there is something that needs to be done to update or change an existing Azure Web App, I can confirm that ANCMv2 _is not_ deployed.  As I said, every time my app publishes I have to go update the web.config (via Kudu) and set it back to ANCM.  I don't want to change my project, because I want to take advantage of ANCMv2 when it's available, but it seems to be taking a long time to get deployed.

**Comment by Axel3232** [comment]
Ping... 
Still not deployed in my region (France)....

**Comment by stap123** [comment]
Any update on this?
