### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.12285

### ISSUE THREAD

**Issue by pragnagopa** [Azure/app-service-announcements-discussions#80]
Discussion issue for the Azure Functions Runtime release 2.0.12285

**Comment by dabutvin** [comment]
> Enables Azure Monitoring via App Setting AZURE_MONITOR_ENABLED

can you tell us more about azure monitor?

Is this something we should turn on in our individual function apps?

**Comment by brettsam** [comment]
@dabutvin -- this is a Private Preview feature we're rolling out for your Function Logs to be directed to [Azure Monitor diagnostic logs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-overview). It's disabled behind-the-scenes right now but we'll share some details on how to get enrolled in the private preview in the near future. Just setting this value won't do anything as we'd need to do some whitelisting of subscriptions on our side as well.

Since it's a little confusing, we'll remove it from the release notes.

**Comment by tjgalama** [comment]
It looks like redirects from HTTP triggered functions don't work anymore. 
see also issue [Returning a RedirectResult with a URL causes NullReferenceException](https://github.com/Azure/azure-functions-host/issues/3986)

**Comment by pragnagopa** [comment]
Fix for issue https://github.com/Azure/azure-functions-host/issues/3986 will be part of next release.

**Comment by TurtleBeach** [comment]
This release, or something else between January 21 and today, appears to have BROKEN using System.getenv("APP_SETTING_NAME")  in the Java Runtime. The key-value pairs appear in APP_SETTINGS, but Java code using System.getenv("") is not seeing the keys. There have been no changes to the function whatsoever. And just to be sure, I stopped and restarted, with the same effect (i.e., APP_SETTINGS are not being read).
This is, to put it mildly, extremely aggravating. This is a basic functionality which you ostensibly set in stone months ago.

**Comment by pragnagopa** [comment]
@TurtleBeach - Add App setting FUNCTIONS_WORKER_RUNTIME set to java. Note this app setting is added if you deploy function app using azure function maven plugin.
Root cause issue https://github.com/Azure/azure-functions-host/issues/4026

**Comment by TurtleBeach** [comment]
Now the tools are broken. Specifically, I updated Core SDK, and supposedly the core tools (npm I -g....), both of which returned no errors. I used the mvn archetype ... to create a new HTTP trigger function expecting it to use all the updated tools and to create a new POM that I can use as a guide to update POMs for existing projects. The new project will build (in Visual Studio code, or from command line), but will not run (mvn azure-functions:run). The staging directory is recognized, but then "func is not recognized as an internal or external command". The reported error is "Azure core tools not found". The azure command line az --version reports 2.0.45. This is again aggravating as hell. I (and presumably anyone else trying to work with Java functions) have to spend time debugging the platform, rather than working on the application - all the while being charged by Microsoft for everything that happens on Azure. Not a happy camper. Please tell me where the core tools are supposed to be so that I can try to figure out why they are not there, or maybe put wherever they are in the path.

**Comment by TurtleBeach** [comment]
It is now working, though I do not know why (which in itself is troubling). I noticed two references to sonatype repositories in the pom created for the new HTTP trigger function, and I do not see a .csproj file for that function. I removed the sonatype references (though I am not certain that had any effect one way or another), and did nothing about the non-existent .csproj file. I also reinstalled core tools.
I am now seeing 2.0.12285 as the runtime locally and on azure. The pom is using maven plugin 1.2.1 and java library 1.2.0. As several people noted/questioned several weeks ago - why don't you concisely summarize (say, in release notes) what runtime, maven plugin, and library are considered current when you release a runtime? It may be crystal clear to you who do the development but leaves the rest of us to hope and pray.
