### ISSUE TITLE
Unable to load DLL 'sni.dll' on .NET Core 2.0

### ISSUE THREAD

**Issue by sireza** [Azure/app-service-announcements-discussions#9]
We have migrated one of our app to .NET Core 2.0. The app runs fine in my development PC, but when deployed to Azure, we are getting this message:

```
System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
   at System.Data.SqlClient.SNILoadHandle..cctor()
```

From what I can tell, this is a part of an internal nuget package 

`runtime.win-x64.runtime.native.system.data.sqlclient.sni`

Is it possible that 'sni.dll' got missed in the recent .NET Core 2.0 deployment to Azure App Service?

**Comment by 1402Mike1402** [comment]
You check this [https://github.com/dotnet/corefx/issues/21766]

**Comment by ericstj** [comment]
/cc @corivera @saurabh500
Can you share your `CSProj` and `project.assets.json` from your `obj` directory?  Also it'd be good to understand what steps you are doing to "deploy to azure".  Thanks!

**Comment by sireza** [comment]
So we've managed to "work around" it.

The culprit is the package "Hangfire.SqlServer" which depends on "System.Data.SqlClient" version => 4.**1**.0

Looks like netcore 2.0 requires version 4.**4**.0 

So we've added the package "System.Data.SqlClient" explicitly into our project, and the problem went away.

Still doesn't explain why it works on our dev machines though...

**Comment by ericstj** [comment]
Perhaps you're running under a different RID on your dev machines?  The older package only targeted win7-* and later RIDs.  New one targets win-* RIDs.  See https://github.com/dotnet/corefx/issues/19154.  If you were publishing with a win-* RID that would cause the error since the older packages didn't support that.

Also, this same issue existed in 1.x for similar reasons, see https://github.com/dotnet/corefx/issues/14085#issuecomment-263709979

/cc @vijayrkn
